### ISSUE TITLE
Change Default Metrics Bind Port

### ISSUE THREAD

**Issue by kareem-rady** [aws/aws-network-policy-agent#45]
Issue:
- The default metrics port used is a commonly used port -> 8080
  
Since the network policy agent is now included by default with the VPC CNI add-on, it can possibly break existing workloads that are using port 8080

Resolution:
Please update the default metrics bind address "metrics-bind-addr" to use another less commonly used port e.g. 8162

Discussed here : https://github.com/aws/amazon-vpc-cni-k8s/issues/2539

**Comment by kareem-rady** [comment]
Thanks it is unfortunately not being exposed as a possible configurable parameter in the aws managed VPC CNI addon therefore it will always deploy with port 8080 
A simplle quick change would be to just change the default port to a less commonly used port

**Comment by jayanthvn** [comment]
We are working on making it configurable with managed add-ons soon. Will provide the ETA.

**Comment by kareem-rady** [comment]
@jayanthvn thanks , appreciate it

**Comment by jtdoepke** [comment]
> it can possibly break existing workloads that are using port 8080

Yep, rolling out a new VPC CNI managed addon version with this port just broke several of our clusters.

We're using Calico for our networking, so all of our cluster's webhooks [have to use](https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks#install-eks-with-calico-networking) `hostNetwork: true`. Unfortunately, a lot of Helm charts for webhooks default to port 8080, such as aws-load-balancer-controller.

I think the worst part though is that the `aws-network-policy-agent` container in the pod spec doesn't declare that it uses port 8080, so Kubernetes doesn't warn us that there's a scheduling conflict with the pods. I had to ssh into an EC2 instance and identify which process was using port 8080 because it wasn't in the pod spec.

**Comment by jaydeokar** [comment]
Closing the issue as we made the metrics port configurable in VPC-CNI release v1.14.1. Managed addon version should be available early next week
