### ISSUE TITLE
Liveness Probes (from host kubelet) are incorrectly blocked

### ISSUE THREAD

**Issue by vaskozl** [aws/aws-network-policy-agent#56]
Upon installing [flux](https://github.com/fluxcd/flux2) with the default network policies, the flux controllers will start CrashLoopBackoffing as the liveness probes are blocked by the controller.

Host to local workload traffic should not be blocked by network policies and is allowed by other CNIs for the purpose of readiness/liveness probes. Furthermore there is no way to know what the IP of the host node is, so to make liveness probes work you'd have to probably allow the entire subnet, which defeats the goal of most ingress policies.

Note that at present some pod's the liveness probe may not fail as netpols can fail to apply completely with the latest release. This may be fixed by https://github.com/aws/aws-network-policy-agent/commit/7e61c86bc5589e2f4866fd45a2b7c16737c88635.

**Comment by achevuru** [comment]
@vaskozl Traffic to/from Node IP will be allowed by default (i.e.,) agent will derive the node's Host IP from IMDS and will automatically add it to the list of allowed CIDRs. Let me validate that and get back..

Also, is this on a v4 or v6 cluster?

**Comment by vaskozl** [comment]
My testing has been on a v6 cluster. The policies can be found on the flux repo:
https://github.com/fluxcd/flux2/tree/9b1e160798220dfe8d79bc72e2bd75d9f3de45eb/manifests/policies

Or generated with `flux install --export`.

**Comment by achevuru** [comment]
@vaskozl  Validated that (http based) liveness/readiness probes work fine for pods with active Network policies in both IPv4 and IPv6 clusters.

Issue with flux is due to `allow-scraping` policy selecting all the pods on the cluster on ingress and allowing them only for port 8080 and TCP. This policy selects host networking pods running on the cluster as well (For ex: kube-proxy and aws-node pods) and host networking pods share the same IP as the node IP.

Although, we allow ingress and egress traffic to node IP by default across all ports and protocols, the above policy resulted in narrowing down the allowed port + protocol combo to 8080 and TCP for Node IP in ingress for these pods. Flux pods have http probes configured for liveness/readiness but on ports 9xxx and so the liveness/readiness probes were rejected as kubelet will use the node IP as the source IP for the probes. We will address the issue in the agent to account for conflicts between policies selecting host networking pods and node IP.

**Comment by jayanthvn** [comment]
PR is merged, will close the issue.
